In [1]:
import torch

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
type(x)

torch.Tensor

In [5]:
x.size()

torch.Size([12])

In [6]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

In [9]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [10]:
x.reshape(3,-1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [13]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [17]:
torch.randn(3,4) # values from normal distribution with mean 0 and std 1

tensor([[ 0.9552, -1.0160, -0.7621, -1.0982],
        [ 0.0365,  1.8793,  2.0808,  0.4024],
        [-0.7252,  0.1213, -0.4254, -0.3005]])

In [19]:
torch.tensor([
    [1,2,3,4],
    [2,4,3,1],
    [1,4,2,3]
])

tensor([[1, 2, 3, 4],
        [2, 4, 3, 1],
        [1, 4, 2, 3]])