In [2]:
import torch

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
type(x)

torch.Tensor

In [5]:
x.size()

torch.Size([12])

In [6]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

In [8]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
x.reshape(3,-1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [10]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
torch.randn(3,4) # values from normal distribution with mean 0 and std 1

tensor([[-1.7902, -0.1230, -0.4658,  0.1873],
        [ 1.3251, -0.1093, -0.6758,  0.7939],
        [ 1.0482, -0.5820, -0.1105,  0.6233]])

In [13]:
torch.tensor([
    [1,2,3,4],
    [2,4,3,1],
    [1,4,2,3]
])

tensor([[1, 2, 3, 4],
        [2, 4, 3, 1],
        [1, 4, 2, 3]])

In [20]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [21]:
X[1]

tensor([4., 5., 6., 7.])

In [22]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [24]:
X[1:3,2:4]

tensor([[ 6.,  7.],
        [10., 11.]])

In [26]:
torch.exp(X) # e to the X, element wise

tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 1.4841e+02, 4.0343e+02, 1.0966e+03],
        [2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]])

In [28]:
x = torch.randn(4)
y = torch.randn(4)
x, y

(tensor([ 1.2023,  0.5518, -0.8749,  0.1238]),
 tensor([ 0.8988, -2.3548, -0.7928,  0.0768]))

In [29]:
x + y # lifted element wise operations

tensor([ 2.1011, -1.8030, -1.6677,  0.2006])

In [30]:
x * y # also element wise

tensor([ 1.0807, -1.2994,  0.6936,  0.0095])

In [32]:
x @ y # dot product

tensor(0.4843)

In [38]:
torch.stack((x, x * 2, y), axis=0)

tensor([[ 1.2023,  0.5518, -0.8749,  0.1238],
        [ 2.4045,  1.1036, -1.7497,  0.2476],
        [ 0.8988, -2.3548, -0.7928,  0.0768]])

In [39]:
torch.stack((x, x ** 2, y ** 2), axis=1)

tensor([[ 1.2023,  1.4455,  0.8079],
        [ 0.5518,  0.3045,  5.5451],
        [-0.8749,  0.7654,  0.6285],
        [ 0.1238,  0.0153,  0.0059]])

In [40]:
x < y

tensor([False, False,  True, False])

In [41]:
x.sum()

tensor(1.0030)

In [46]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(-1,2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [47]:
a + b # with broadcasting

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [50]:
before = id(y)
y = x + y
id(before) == id(y)

False

In [56]:
z = torch.ones_like(x)
print(f"id(z): {id(z)}")
z[:] = x + y # This performce in-place addition
print(f"id(z): {id(z)}")
z

id(z): 4563777984
id(z): 4563777984


tensor([11.1125, -3.2017, -8.5025,  1.0970])

In [57]:
before = id(x)
x += y # This performce in-place addition
id(x) == before

True

In [66]:
a = torch.randn(12).reshape(1,3,4)
b = torch.randn(12).reshape(3,1,4)
a, b

(tensor([[[-0.4827, -0.6823, -3.1332,  0.6740],
          [ 0.8607,  2.6300, -0.1566,  0.2311],
          [ 1.8090,  0.5589, -1.0644, -0.2867]]]),
 tensor([[[-1.2544, -1.1729,  0.9106, -1.1826]],
 
         [[-1.2292,  0.2606,  0.8069, -0.8796]],
 
         [[ 1.1741,  1.5699,  0.6242,  0.3979]]]))

In [67]:
a + b

tensor([[[-1.7370, -1.8552, -2.2226, -0.5086],
         [-0.3937,  1.4571,  0.7540, -0.9515],
         [ 0.5546, -0.6140, -0.1538, -1.4693]],

        [[-1.7119, -0.4217, -2.3264, -0.2056],
         [-0.3685,  2.8906,  0.6502, -0.6485],
         [ 0.5798,  0.8195, -0.2575, -1.1663]],

        [[ 0.6914,  0.8876, -2.5090,  1.0719],
         [ 2.0348,  4.1999,  0.4675,  0.6289],
         [ 2.9831,  2.1288, -0.4402,  0.1112]]])